### ISSUE TITLE
Target path with spaces

### ISSUE THREAD

**Issue by rdavid2** [deajan/osync#191] opened 2020-04-19 19:52 UTC
**Describe the bug**
Synchronize a ssh target with spaces it does not work form me, is a bug or I do something wrong?

**To Reproduce**
Set a path with spaces on target.
Path exists in destionation and has the correct permisions, for example:
ssh://user@host//media/magatzem/osync prova

I try with:
- name with space (osync prova)
- name escaping  space with \ (osync\ prova)
- name escaping space with \\ (osync\\ prova)
- executing directly from console
- executing from config file

**Expected behavior**
La misma prueba sin espacios funciona correctamente

**Logs**
bash: line 110: /media/magatzem/osync: Permission denied
bash: line 111: /media/magatzem/osync: Permission denied
mkdir: cannot create directory '/media/magatzem/osync\ prova': Permission denied
TIME: 0 - Cannot create remote replica deletion directory in [/media/magatzem/osync\ prova/.osync_workdir/deleted].
TIME: 5 - Cannot copy back the failed deletion list to initiator replica.

**Desktop (please complete the following information):**
Ubuntu 20.04

**Additional context**

**Comment by deajan** [comment] 2020-04-19 22:37
What version of osync do you use ?
Please have a test run with latest master if not done.

**Comment by rdavid2** [comment] 2020-04-19 23:27
I think it is the latest version: cloned yesterday from git
osync 1. 2 017032101

**Comment by deajan** [comment] 2020-04-19 23:40
Yep, that's v1.2. Current git master v1.3-prerc1 has fixes that should address that issue. Please try with latest git master.

**Comment by zhangzhishan** [comment] 2020-04-22 02:24
> 
> 
> Yep, that's v1.2. Current git master v1.3-prerc1 has fixes that should address that issue. Please try with latest git master.

I run v1.3-prerc1, it still has the same problem.

```
TIME: 0 - This is an unstable dev build [2020012302]. Please use with caution.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Wed Apr 22 10:20:28 CST 2020 - osync 1.3.0-prerc1 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [sync_personaldropbox_to_sync] launched as root@xxx(PID 10746)
TIME: 0 - Checking minimum disk space in local replica [/mnt/d/localdropbox/Dropbox (Personal)/].
TIME: 0 - Checking minimum disk space in local replica [/mnt/c/Users/xxx/Dropbox (Personal)/].
head: cannot open '/mnt/c/Users/xxx/Dropbox' for reading: No such file or directory
head: cannot open '(Personal)/.osync_workdir/lock' for reading: No such file or directory
```

**Comment by deajan** [comment] 2020-04-22 07:10
Cannot reproduce. Would you mind giving me your anonymized config file ?

**Comment by zhangzhishan** [comment] 2020-04-22 08:36
Thank you, this is my [config file](https://gist.github.com/zhangzhishan/1dd3f596d06d704553db99fd45ffc2c3). 

I am using it in wsl, I am not sure whether it is different.

**Comment by zhangzhishan** [comment] 2020-04-22 08:41
In fact, I have run this service for about two months, but failed yesterday. So I tried to update the osync version and failed again.

**Comment by deajan** [comment] 2020-04-29 10:39
Sorry for the delay. While trying to reproduce your issue, I actually found an issue with remote characters containing parenthesis. This has been fixed in https://github.com/deajan/osync/commit/a912a7d7c39d671d8cd969f9717c4260b3b99f74

But it does not seem related to your permission issues.

Would you mind anyway to retry with latest git master that includes the fix ?

**Comment by zhangzhishan** [comment] 2020-05-02 10:54
Have found problem and fixed. Please help review.

**Comment by deajan** [comment] 2020-05-03 08:11
@zhangzhishan Nice catch, thank you ;) I've now ensured that all subshell filenames are quoted.

**Comment by deajan** [comment] 2020-05-04 06:52
@rdavid2 @zhangzhishan Can I consider this issue solved ?

**Comment by zhangzhishan** [comment] 2020-05-04 09:58
It's okay for me.

**Comment by deajan** [comment] 2020-05-12 12:24
Closing this since it seems resolved.

**Closed by deajan** 2020-05-12 12:24 UTC
