### ISSUE TITLE
Double Master Setup

### ISSUE THREAD

**Issue by Mohammed-JS-Khan** [deajan/osync#107] opened 2017-06-13 20:00 UTC
Is is possible to use osync in a master-master setup? Where there are two hosts that can both add or remove file to/from a certain directory, and every time that occurs on one master, it syncs to the other master. I'm worried about the 600s delay and the file monitoring trigger which may cause an infinite loop.

**Comment by deajan** [comment] 2017-06-13 20:42
osync cannot monitor targets as of today, so it's always initiator-target setups where only initiator is monitored.
The 600s delay can be adjusted, and no concurrent runs will happen.
Infinite loops would only happen if you add files for an infinite time.

There could be a osync helper service on target that on file modification quickly uploads a file to initiator to trigger a sync indeed.

**Comment by Mohammed-JS-Khan** [comment] 2017-06-13 20:47
Thanks for the quick reply.

I was specifically wondering what would happen if we had 2 sets of osync, each monitoring its own master and syncing with a target. Would that work at all?

**Comment by deajan** [comment] 2017-06-13 20:56
This would indeed lead to an infinite loop.
What's your usecase ? Instant sync ? Tried unison ?

**Comment by Mohammed-JS-Khan** [comment] 2017-06-13 21:00
Ah okay fair enough.

Yeah I have two servers behind a load balancer that can be used in any order. In case one of them is used, I want the other one to be updated and vice versa.

I have looked into unison, but its slightly old and isn't being developed anymore. Plus I don't have root access to install it with, and building from source is a PITA as it requires OCaml which ALSO needs to be built from source.

Thanks for your help though, I might try out the helper service idea instead!

**Comment by deajan** [comment] 2017-06-13 21:07
I'll quickly write a helper service next week since it was on my todo list for a long while.

**Comment by Mohammed-JS-Khan** [comment] 2017-06-13 21:08
Whoops sorry.

That sounds good! Thanks

**Comment by archon810** [comment] 2017-08-08 22:34
I'm also interested in a multi-master sync, which I currently have working using lsyncd, except it fails with large files that take a while to copy.

I'm tracking the issue here https://github.com/axkibe/lsyncd/issues/458.

I like the approach of having sync threads running on all servers, not a single sync thread and then a helper service on secondary servers because I'd like to be able to not have a single point of failure when the master goes down. Every server should act as a master. In my case, I have 4 servers.

**Comment by deajan** [comment] 2017-08-09 12:13
osync v1 won't be multimaster. Target helper service exists as of today but needs a minimum love indeed.

**Comment by deajan** [comment] 2018-07-03 15:19
Closing as duplicate of #108.

**Closed by deajan** 2018-07-03 15:19 UTC
Labels: enhancement
