### ISSUE TITLE
Sync a single file

### ISSUE THREAD

**Issue by henrygodwin** [deajan/osync#210] opened 2020-08-19 12:20 UTC
**Describe the bug**
rsync allows a single file to be synced (rather than a directory) - my use case requires just a single file to be synced.
rsync example: rsync -avz /var/www/public_html/.htaccess root@<remote-ip>:/var/www/public_html/

**To Reproduce**
Specify a file rather than a folder in INITIATOR_SYNC_DIR conf setting.

**Expected behavior**
It would be nice if it was possible to specific a single file rather than directory. Currently I have to use the rsync **include** option to specify my file and then use the **exclude** with a wildcard to exclude everything else.

This leads me to an additional problem for me... I'm using inotify-tools version 3.14-8 (which is the latest in the Ubuntu repo) and it doesn't seem to to support the --include option. When running in daemon mode I see the following error in the logs:

inotifywait: unrecognized option '--include="file.json"'
inotify error  detected, waiting 60 seconds before running next sync.

**Logs**

TIME: 1 - Failed to check remote replica.
TIME: 0 - Remote replica path [/test/path/file.json/] does not exist / is not writable.
TIME: 2 - Cancelling task.

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic Beaver
 - Bitness x64
 - Shell bash

**Additional context**
None

**Comment by deajan** [comment] 2020-09-21 20:43
Sorry, it is totally out of scope for osync to sync a single file, by design.
You're better of running `rsync -u` I think here.

**Comment by dereks** [comment] 2021-01-12 21:04
> Sorry, it is totally out of scope for osync to sync a single file, by design.

I do not understand why you would write this. Sometimes we want to sync one file, not a directory. 

The Dropbox client does it. Clearly there is a use case.

Rsync already supports single files. Why would you want to code in this anti-feature rather that just allowing it in osync.sh?

**Comment by deajan** [comment] 2021-01-13 22:28
@dereks osync is stateful, meaning it needs a folder to store states.
For single files, you definitly won't need more than two rsync -u lines...

**Closed by deajan** 2021-01-13 22:28 UTC
Labels: question

**Comment by flux627** [comment] 2021-07-19 21:09
Also disappointed this can't do single files. I'm looking to bidirectionally sync specific files using the daemon functionality.

**Comment by deajan** [comment] 2021-07-20 07:41
Again, the whole design of osync needs directories to work.
You still can specify single directories to sync and then add a rsync pattern to acheive single file sync, but as I said, this is really overkill for such a basic task.

**Comment by flux627** [comment] 2021-07-23 18:31
What, then, would be the simplest way of achieving 2-way sync on a single file?
