### ISSUE TITLE
osync errors on Gentoo due to missing VERSION in /etc/os-release

### ISSUE THREAD

**Issue by kozross** [deajan/osync#134] opened 2018-02-14 06:50 UTC
When you run osync.sh on Gentoo, you get this error:

    TIME: 0 - Cannot get value for [VERSION] in config file [/etc/os-release].

This causes an abnormal (that is, erroneous) exit. Given that this field is optional (and doesn't make sense for Gentoo in any case), this seems a little excessive.

**Comment by deajan** [comment] 2018-02-14 07:24
Looks like a duplicate of #126 to me.

**Comment by deajan** [comment] 2018-03-15 18:53
Closing since this is already fixed in master

**Closed by deajan** 2018-03-15 18:53 UTC
