### ISSUE TITLE
Wrong ACL on directory when set on remote host

### ISSUE THREAD

**Issue by poleprogger** [deajan/osync#82] opened 2016-11-20 11:37 UTC
I discovered that there is an issue with ACL on a directory when you change it from a remote host.
Version:1.1.5
Steps to reproduce:
1. Create directory "testdir" and a file inside named "testfile". Doesn't matter whether on the master or slave.
2. Run osync
3. On the remote host: write something into the file and save
4. On the remote host: setfacl -m u:someuser:rwx -R testdir
5. Run osync 
6. Check ACL on sync master. 
When i do that i can see that the directory has lost the ACL setting from the remote host. Although the file has the correct acl with someuser. 

PS: Great software, saved me some headache :-)

**Comment by deajan** [comment] 2016-11-20 16:25
Sorry, I am unable to reproduce this problem following your instructions.
As for step 1, it should matter whether it as been tested on initiator or target. I've tested both, they seem to work.

I've updated unit tests with more ACL tests also and I can't find the problem.

Can you post your config file ?

**Comment by deajan** [comment] 2016-12-05 10:25
Closing this because of insufficient info. Feel free to re open if you can provide additional data.

**Closed by deajan** 2016-12-05 10:25 UTC
Labels: invalid
