### ISSUE TITLE
Permissions and ownership not correctly synched and suggested solution

### ISSUE THREAD

**Issue by vstefanoxx** [deajan/osync#42] opened 2016-01-09 10:23 UTC
Hello.
There is the following situation where osync doesn't correctly synchronize permissions and ACLs:
- one files is correctly synchronized
- slave modify ACL only (or ownership or other permissions)
- master run the synchronization (with PRESERVE_ACL=yes) and osync wrongly copy the ACL from master to slave, and not the contrary

Problem is that rsync compare the mtime of source and destination files to decide which one is more recent, but modificatrion of ACL and other permissions only modify the ctime, so the two files still have the same mtime and rsync synchronize the files in the direction run first.

My proposition is to run a similar script before the first "sync_update":
```
#!/bin/bash
scriptname="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
local_path="$1"
remote_ip="$2"
remote_path="$3"
RSYNC_ARGS="$4"

[ -z "$RSYNC_ARGS" ] && RSYNC_ARGS="-rlptgoD -A -X -z -E"
RSYNC_ARGS="$(<<<"$RSYNC_ARGS" sed -e 's/--checksum[[:space:]]*//')"

local_path="${local_path%%/}"
remote_path="${remote_path%%/}"
tmp_file="/tmp/${scriptname}_$RANDOM"

/usr/bin/rsync --rsync-path="rsync" $RSYNC_ARGS -ui -e "/usr/bin/ssh -C -i /root/.ssh/id_rsa -p 22" --exclude ".osync_workdir" \
	--exclude-from="$local_path/.osync_workdir/state/master-deleted-list-sync_test" \
	--exclude-from="$local_path/.osync_workdir/state/slave-deleted-list-sync_test" \
	"$local_path/" root@$remote_ip:"$remote_path/" --dry-run | \
	grep -Ev "^[^ ]*(c|s|t)[^ ]* " | \
	grep -E "^[^ ]*(p|o|g|a)[^ ]* " | \
	sed -e 's/^[^ ]* //' >"$tmp_file"
	
cd "$local_path"
cat "$tmp_file" | xargs -I {} stat -c '%n|%Z|%Y' "{}" | sort >"${tmp_file}.1"

cat "$tmp_file" | /usr/bin/ssh -C -i /root/.ssh/id_rsa -p 22 root@$remote_ip "cd \"$remote_path\" ; xargs -I {} stat -c '%n|%Z|%Y' \"{}\"" | sort >"${tmp_file}.2"

join -j 1 -t \| -o 1.1,1.2,2.2 "${tmp_file}.1" "${tmp_file}.2" | awk -F'|' '{if ($2 < $3) print $1}' | \
	/usr/bin/rsync --rsync-path="rsync" $RSYNC_ARGS -ui -e "/usr/bin/ssh -C -i /root/.ssh/id_rsa -p 22" \
	root@$remote_ip:"$remote_path/" "$local_path/" --files-from=-

rm -f "$tmp_file"*
```

Probably this solution is not the most efficient, because run a one more rsync command (also if with --dry-run option) before the synchronization of file content inside sync_update.
An alternative could be to use "find" to report the list of files with mtime and ctime, but maybe it's more difficult to give support for RSYNC_EXCLUDE_* options.
Another alternative, only possible including this code inside osync.sh script, is to write the output unmodified of rsync --dry-run to file, then run two rsync with " --files-from=-", one for acls, one for real copy, conveniently grepping the input file.

Stefano

**Comment by deajan** [comment] 2016-01-11 12:41
Hello Stefano,
In order to investigate this issue, can you tell me if you did all the tests with osync v1.1 or v1.0 ?

**Comment by vstefanoxx** [comment] 2016-01-11 19:00
Last stable, v1.01.

It depends on an rsync issue, probably a design decision more tha a bug, and if not specifically addressed in new development version of osync it should still be there.

It can be replicated also with rsync only, without using osync.

To replicate the issue:
- file a.txt is present in master and slave replica, and it's synchronized
- command
```
stat -c '%n|%Z|%Y' a.txt
```
give same results in both replicas:
```
a.txt|1452537285|1452537285
```
- let's change ACL (or ownership or other permissions) of a.txt in slave replica:
```
setfacl -m user:<some user>:rwx a.txt
```
- stat command in slave replica give now:
```
a.txt|1452537997|1452537285
```
It means that modification time (1452537285) is still the same as in master replica, but change time (1452537997) is more recent
- running rsync synchronization from master to slave copy master replica's ACLs to slave replica's ACL, undoing the modification in slave replica

If before running rsync, we "touch" a.txt in slave replica, then modification and change time of file a.txt in slave replica would be the same and more recent than the ones in master replica: in that case rsync from master to slave wouldn't copy ACL because it would detect than a.txt in slave replica is more recent then the one in master replica.

**Comment by vstefanoxx** [comment] 2016-01-15 11:47
Do you think is possible to solve this problem inside osync, or should I hack it?

**Comment by deajan** [comment] 2016-02-13 17:25
I finally had time to play around with this bug.
Indeed the mtime only behavior is by design in rsync, which wasn't basically created to handle syncs.

I've read your script and it's a solution, but is probably not portable because of stat
I'll probably try to create a two way sync_acl function to adress this before release 1.1 which was supposed to happen soon.

I must investigate the portability of this solution before integration.
What system do you run osync on ?
Would you mind making some beta testing ?

**Comment by vstefanoxx** [comment] 2016-02-16 14:16
My system is Debian 8.2, rsync 3.1.1.
I can do some beta testing when you have something ready.

**Comment by deajan** [comment] 2016-02-19 00:15
I really got headaches merging your script into the osync codebase...
Nevertheless, I have pushed a dev version that might fix your problem. It's still work in progress, but perhaps you can tell me if this resolves your issue ?

**Comment by deajan** [comment] 2016-02-19 08:30
Before I forget, i've set the sync_attr code as experimental because it's not tested yet.
So you have to run osync with:
`SYNC_ATTR=1 ./osync.sh your.conf`

**Comment by deajan** [comment] 2016-02-22 23:54
Any time to play with this yet ?

**Comment by vstefanoxx** [comment] 2016-02-23 07:36
Not yet. I'm planning to test it tomorrow, I'll let you know

2016-02-23 0:54 GMT+01:00 Orsiris de Jong <notifications@github.com>:

**Comment by deajan** [comment] 2016-02-27 10:50
I've found a nicer way to handle this for my osync2 rewrite which works as multimaster via inotify.
Whenever a file gets modded (either by setfacl or anything else), update it's mtime with ctime.
This way, rsync would handle them as newer version of files and update ACLs accordingly.
Do you see any drawbacks with this ?

**Comment by vstefanoxx** [comment] 2016-02-29 07:30
If I understand well, osync2 will work as a service in background and
detect modification with inotify.
The drawback of updating mtime through inotify hooks is that if inotify
detection stops or it doesn't start for some reason, we will have a
misalignment in mtime and ctime and next synchronization will fail to
correctly synchronize folders.
Ideal situation is to be able to synchronize correctly with the only
requirement being tha avaibility of folders to be synchronized.

I suppose osync2 support realtime synchronization with inotify but also
"batch" syncronization for first synchronization and periodic ones.
Maybe mtime and ctime synchronization can also be done optionally before
batch syncronization.

I'm sorry still didn't have time to test the experimental SYNC_ATTR code...

2016-02-27 11:50 GMT+01:00 Orsiris de Jong <notifications@github.com>:

**Comment by deajan** [comment] 2016-02-29 19:09
osync2 will be a radically different beast, with multimaster capability, and file move detection.
That's why it is supposed to run as daemon, and yes, if the daemon stops, it won't be able to detect deletions, at least for now. There's a directory snapshot service that could achieve what you're looking for, but it's not my main option as this would only be useful in recovery state.

osync1 will continue to exist and support what you're searching for. Please tell me if you happen to get time to test the osync1 attr code.

Regards,
Ozy.

**Comment by deajan** [comment] 2016-03-30 07:18
Merged into master, tested.

**Closed by deajan** 2016-03-30 07:18 UTC
Labels: bug, enhancement

**Comment by vstefanoxx** [comment] 2016-03-31 10:06
Thank you, great work.

I'm sorry I couldn't help with testing, my work brought me far from file
synchronization lately.
Looking forward to have occasion to try it again (especially osync2).

2016-03-30 9:18 GMT+02:00 Orsiris de Jong <notifications@github.com>:
